[phases.install]
commands = [
  "npm install --omit=dev"
]

[phases.build]
commands = [
  "npm -w @openworld/shared run build",
  "npm -w server run build"
]

[start]
cmd = "node apps/server/dist/index.js"
